"""GAMESS-UK input decks (AV-QM-006), from Avogadro's dialog.

`gamessukinputdialog.cpp:generateInputDeck` (`:271-403`) writes a directive file: a comment
header, a `title` block, `iprint vectors` for a run that moves the atoms, the multiplicity and
the charge, the geometry as either a `geometry angstrom` block or a `zmatrix angstrom` one, the
basis, the run type, the SCF type and `enter`. The lists are its four combos
(`getRunType`, `getScfType`, `getBasisType` and the DFT functional switch inside `getScfType`),
and its enums and combo items are in the same order throughout (`gamessukinputdialog.h:48-52`)
-- as is `resetClicked` (`:161-174`), which unlike the Q-Chem and Psi4 dialogs really does
restore what the form opened with.

This is the second generator that writes a transition-state deck: `runtype saddle`, with the
Cartesian geometry marked `all` so GAMESS-UK builds the Z-matrix a saddle-point search needs
(`:301-304`).

Four departures.

* **Two of the six basis labels name something the deck does not ask for.** The combo reads
  `6-31G(d)` and `6-31G(d,p)` at indices 2 and 3, and `getBasisType` writes `6-31G` and `6-31G*`
  for them (`:479-496`) -- so choosing the polarized basis gets an unpolarized one, and choosing
  the doubly polarized one gets a singly polarized one. We write exactly the six keywords the
  dialog writes and give each the name of what it writes, so nothing is promised that the deck
  does not ask for.
* **`runtype optimze`** -- an optimization from a Z-matrix is spelled with the `i` missing
  (`:411`), which GAMESS-UK does not read. Written `optimize` here. The Cartesian spelling,
  `optxyz`, is correct there.
* **Whitespace is normalized**: the dialog writes `title ` with a trailing space (`:283`) and
  `basis  ` with two (`:390`). Neither means anything to GAMESS-UK and neither is written here.
* The header says the file was generated by Atomscope rather than by Avogadro, which would not
  be true. The pointer to the manual is kept, as the dialog wrote it.

And one gap that is said rather than inherited: the theory combo is HF, DFT and MP2, with no UHF
or GVB entry, so whatever the multiplicity the deck writes `scftype rhf`. What GAMESS-UK makes of
that at `mult 3` is a question for its manual rather than for this source, so `plugin.py` says
what the deck asks for and leaves the judgement to whoever runs it.
"""

from __future__ import annotations

from atomscope.chem.zmatrix import zmatrix
from atomscope.model import Structure

RUN_TYPES = {
    "energy": "scf",
    "optimize": "optxyz",
    "transition_state": "saddle",
    "frequencies": "hessian",
}
"""`getRunType` (`:405-422`), without the `runtype` the deck prefixes. An optimization from a
Z-matrix is `optimize` rather than `optxyz` -- see `_run_type`."""

THEORIES = {"rhf": "rhf", "dft": "dft", "mp2": "mp2"}
"""`getScfType`; DFT is the one that reaches for a functional."""

THEORY_LABELS = {"rhf": "HF", "dft": "DFT", "mp2": "MP2"}

FUNCTIONALS = ("svwn", "blyp", "b3lyp", "b97", "hcth", "ft97")
"""The DFT switch of `getScfType` (`:436-459`); the combo spells them in upper case."""

BASIS_SETS = {
    "sto3g": "sto3g",
    "b321g": "3-21G",
    "b631g": "6-31G",
    "b631gs": "6-31G*",
    "ccpvdz": "cc-pVDZ",
    "ccpvtz": "cc-pVTZ",
}
"""`getBasisType`, keyword for keyword."""

BASIS_LABELS = {
    "sto3g": "STO-3G",
    "b321g": "3-21G",
    # the combo calls these two 6-31G(d) and 6-31G(d,p), which is not what it writes
    "b631g": "6-31G",
    "b631gs": "6-31G*",
    "ccpvdz": "cc-pVDZ",
    "ccpvtz": "cc-pVTZ",
}
"""What each entry writes, which is what it is named here."""

MOVING_RUNS = ("optimize", "transition_state")
"""The two that make the deck print its orbital vectors (`gamessukinputdialog.cpp:286-290`)."""


def _cartesian(structure: Structure) -> list[str]:
    """The Qt field widths of `:307-313`: three coordinates of 12, then the number and the symbol
    of 4 each."""
    return [
        f"{a.position[0]:12.8f}{a.position[1]:12.8f}{a.position[2]:12.8f}"
        f"{a.atomic_number:>4d}{a.element:>4}"
        for a in structure.atoms
    ]


def _zmatrix(structure: Structure) -> list[str]:
    """`zmatrix angstrom` and its variables, in the shape `:325-387` writes them.

    The references are 1-based there, and the variable names carry the row's own number, so the
    second atom's distance is `r2`. A negative torsion is written as its positive equivalent,
    which `chem/zmatrix.py` already does.
    """
    rows = zmatrix(structure)
    lines: list[str] = []
    variables: list[str] = []
    for i, row in enumerate(rows):
        line = f"{row.element:>3}"
        for name, reference, value in (
            ("r", row.a, row.distance),
            ("a", row.b, row.angle),
            ("d", row.c, row.torsion),
        ):
            if reference is None or value is None:
                break
            variable = f"{name}{i + 1}"
            line += f"  {reference + 1:>3}  {variable:>4}"
            variables.append(f"   {variable}{value:15.5f}")
        lines.append(line)
    return ["zmatrix angstrom", *lines, " variables", *variables, "end"]


def _run_type(task: str, coordinates: str) -> str:
    """The `runtype` line, with `getRunType`'s one typo repaired."""
    if task == "optimize" and coordinates != "cartesian":
        # the dialog writes `runtype optimze` here, which GAMESS-UK does not read
        return "runtype optimize"
    return f"runtype {RUN_TYPES[task]}"


def _scf_type(theory: str, functional: str, *, direct: bool) -> list[str]:
    """`getScfType` (`:424-473`). DFT is the only one that answers in two lines, and only in
    direct mode: without it the deck names no `scftype` at all, as the dialog leaves it."""
    if theory == "dft":
        return ["scftype direct", f"dft {functional}"] if direct else [f"dft {functional}"]
    return [f"scftype direct {THEORIES[theory]}" if direct else f"scftype {THEORIES[theory]}"]


def gamessuk_deck(
    structure: Structure,
    *,
    title: str,
    theory: str = "rhf",
    functional: str = "b3lyp",
    basis: str = "b321g",
    task: str = "energy",
    charge: int = 0,
    multiplicity: int = 1,
    coordinates: str = "cartesian",
    direct: bool = False,
    extra: str = "",
) -> str:
    """One GAMESS-UK deck, in the order Avogadro's dialog writes it."""
    if theory not in THEORIES:
        msg = f"unknown GAMESS-UK theory {theory!r}"
        raise ValueError(msg)
    if functional not in FUNCTIONALS:
        msg = f"unknown GAMESS-UK functional {functional!r}"
        raise ValueError(msg)
    if basis not in BASIS_SETS:
        msg = f"unknown GAMESS-UK basis set {basis!r}"
        raise ValueError(msg)
    if task not in RUN_TYPES:
        msg = f"GAMESS-UK has no run type for {task!r}"
        raise ValueError(msg)

    lines = [
        "# This file was generated by Atomscope",
        "# For more GAMESS-UK input options consult the manual at:",
        "# http://www.cfs.dl.ac.uk/docs/index.shtml",
        "",
        "title",
        title,
        "",
    ]
    if task in MOVING_RUNS:
        lines += ["# Ensure orbital vectors printed after optimisation", "iprint vectors", ""]
    lines += [f"mult {multiplicity}", f"charge {charge}", ""]
    if coordinates == "cartesian":
        # a saddle-point search wants every atom, so GAMESS-UK can build the Z-matrix itself
        header = "geometry angstrom all" if task == "transition_state" else "geometry angstrom"
        lines += [header, *_cartesian(structure), "end"]
    else:
        lines += _zmatrix(structure)
    lines += ["", f"basis {BASIS_SETS[basis]}", "", _run_type(task, coordinates)]
    lines += _scf_type(theory, functional, direct=direct)
    if extra.strip():
        lines += [line.strip() for line in extra.strip().splitlines()]
    lines += ["", "enter"]
    return "\n".join(lines) + "\n"
