# ruff: noqa: E501
"""Task-oriented parameter schema for CP-PAW. Every key maps to a CNTL/STRC location.

The schema exposes what the hands-on course actually varies; the manual's full key set is in
docs/cppaw-analysis.md §3 and can be added incrementally (each spec's ``backend_path`` says
where the value lands).
"""

from __future__ import annotations

from atomscope.schemas import ParameterSchema, ParameterSpec, Preset, Section, VisibleWhen
from atomscope.schemas.engine import Choice
from atomscope.units import Unit

XC_CHOICES = [
    Choice(value=10, label="PBE (GGA)", help="Perdew-Burke-Ernzerhof exchange and correlation"),
    Choice(value=11, label="RPBE (GGA)", help="Hammer's revised PBE"),
    Choice(value=9, label="PW91-LSD + Becke exchange + PBE correlation"),
    Choice(value=8, label="PW91-LSD + Becke-88 exchange + Perdew-86 correlation"),
    Choice(value=7, label="PW91-LSD + Becke-88 gradient correction (exchange)"),
    Choice(value=1, label="LDA: Perdew-Zunger (Ceperley-Alder)"),
    Choice(value=2, label="LDA: Perdew-Wang 91 (Ceperley-Alder)"),
    Choice(value=3, label="Local exchange only (Xα, α=2/3)"),
]

SETUP_CHOICES = [
    Choice(
        value=".75_6.0",
        label=".75_6.0 (course default)",
        help="internal setup family used by all hands-on decks",
    ),
    Choice(value="NDLSS_V0", label="NDLSS_V0"),
    Choice(value="NDLSS_SC_V0", label="NDLSS_SC_V0 (semicore)"),
    Choice(value="HBS", label="HBS"),
    Choice(value="HBS_SC", label="HBS_SC (semicore)"),
]

SCHEMA = ParameterSchema(
    id="cppaw",
    backend="cppaw",
    version=1,
    title="CP-PAW calculation",
    sections=[
        Section(
            id="task",
            label="Task",
            parameters=[
                ParameterSpec(
                    key="task",
                    label="Task",
                    type="enum",
                    default="single_point",
                    choices=[
                        Choice(
                            value="single_point",
                            label="Wave-function optimization (single point)",
                            help="Converge the electrons for fixed atoms",
                        ),
                        Choice(
                            value="forces",
                            label="Forces (electrons + a few damped atomic steps)",
                            help="CP-PAW prints forces only when atoms are propagated (!RDYN)",
                        ),
                        Choice(
                            value="relax",
                            label="Geometry optimization (damped dynamics)",
                            help="!RDYN with automatic friction",
                        ),
                        Choice(
                            value="md",
                            label="Molecular dynamics",
                            help="!RDYN with zero friction and optional Nosé thermostats",
                        ),
                    ],
                    backend_path="CONTROL/RDYN",
                ),
                ParameterSpec(
                    key="start",
                    label="Start from",
                    type="enum",
                    default="scratch",
                    choices=[
                        Choice(value="scratch", label="Scratch (random wave functions, START=T)"),
                        Choice(
                            value="restart",
                            label="Restart file (START=F)",
                            help="continues wave functions and geometry from case.rstrt",
                        ),
                        Choice(
                            value="restart_new_structure",
                            label="Restart file, but take geometry from structure (NEWSTRC=T)",
                        ),
                    ],
                    backend_path="CONTROL/GENERIC/START",
                    help="With START=F CP-PAW ignores the structure file unless NEWSTRC=T (a known trap).",
                ),
                ParameterSpec(
                    key="nstep",
                    label="Time steps",
                    type="integer",
                    default=300,
                    minimum=1,
                    backend_path="CONTROL/GENERIC/NSTEP",
                    help="Upper limit; the autopilot may stop earlier when the energy is converged.",
                ),
                ParameterSpec(
                    key="dt",
                    label="Time step",
                    type="number",
                    default=5.0,
                    minimum=0,
                    exclusive_minimum=True,
                    backend_path="CONTROL/GENERIC/DT",
                    help="atomic units of time (1 a.u. ≈ 0.0242 fs)",
                    unit=Unit.ATOMIC_TIME,
                ),
                ParameterSpec(
                    key="nwrite",
                    label="Report every N steps",
                    type="integer",
                    default=50,
                    minimum=1,
                    backend_path="CONTROL/GENERIC/NWRITE",
                    help="Frequency of detailed protocol reports and restart-file updates.",
                ),
                ParameterSpec(
                    key="etol",
                    label="Energy tolerance",
                    type="number",
                    default=1e-5,
                    minimum=0,
                    exclusive_minimum=True,
                    unit=Unit.HARTREE,
                    advanced=True,
                    backend_path="CONTROL/GENERIC/ETOL",
                    help="Autopilot stops when the energy stays within ETOL for AUTOCONV steps.",
                ),
                ParameterSpec(
                    key="autoconv",
                    label="Convergence window (steps)",
                    type="integer",
                    default=20,
                    minimum=1,
                    advanced=True,
                    backend_path="CONTROL/GENERIC/AUTOCONV",
                ),
            ],
        ),
        Section(
            id="electronic",
            label="Electronic structure",
            parameters=[
                ParameterSpec(
                    key="xc",
                    label="Exchange-correlation",
                    type="enum",
                    default=10,
                    choices=XC_CHOICES,
                    backend_path="CONTROL/DFT/TYPE",
                    reference="manual: !CONTROL!DFT",
                ),
                ParameterSpec(
                    key="vdw",
                    label="Van der Waals correction",
                    type="boolean",
                    default=False,
                    advanced=True,
                    backend_path="CONTROL/DFT/VDW",
                ),
                ParameterSpec(
                    key="epwpsi",
                    label="Plane-wave cutoff (wave functions)",
                    type="number",
                    default=30.0,
                    minimum=1,
                    unit=Unit.RYDBERG,
                    backend_path="CONTROL/FOURIER/EPWPSI",
                    help="30 Ry is sufficient for most applications; test convergence.",
                ),
                ParameterSpec(
                    key="cdual",
                    label="Density cutoff ratio (CDUAL)",
                    type="number",
                    default=2.0,
                    minimum=1,
                    backend_path="CONTROL/FOURIER/CDUAL",
                    help="EPWRHO = CDUAL × EPWPSI; 4 is exact, 2 is usually adequate.",
                ),
                ParameterSpec(
                    key="spin_polarized",
                    label="Spin polarized",
                    type="boolean",
                    default=False,
                    backend_path="STRUCTURE/OCCUPATIONS/NSPIN",
                ),
                ParameterSpec(
                    key="total_spin",
                    label="Total spin S",
                    type="number",
                    default=0.0,
                    minimum=0,
                    unit=Unit.DIMENSIONLESS,
                    backend_path="STRUCTURE/OCCUPATIONS/SPIN[HBAR]",
                    help="In ħ: one unpaired electron = 0.5. Overrides the structure's multiplicity when set to a non-zero value.",
                    visible_when=[VisibleWhen(key="spin_polarized", op="truthy")],
                ),
                ParameterSpec(
                    key="empty_bands",
                    label="Empty bands",
                    type="integer",
                    default=4,
                    minimum=0,
                    backend_path="STRUCTURE/OCCUPATIONS/EMPTY",
                    help="Unoccupied states included in the calculation (needed for LUMO plots and metals).",
                ),
                ParameterSpec(
                    key="occupations",
                    label="Occupations",
                    type="enum",
                    default="fixed",
                    choices=[
                        Choice(value="fixed", label="Fixed (insulators, molecules)"),
                        Choice(
                            value="mermin",
                            label="Mermin functional (metals, fractional occupations)",
                        ),
                    ],
                    backend_path="CONTROL/MERMIN",
                ),
                ParameterSpec(
                    key="electron_temperature",
                    label="Electron temperature",
                    type="number",
                    default=1000.0,
                    minimum=0,
                    unit=Unit.KELVIN,
                    backend_path="CONTROL/MERMIN/T[K]",
                    visible_when=[VisibleWhen(key="occupations", value="mermin")],
                ),
                ParameterSpec(
                    key="mermin_retard",
                    label="Occupation retardation",
                    type="number",
                    default=10.0,
                    minimum=0,
                    advanced=True,
                    backend_path="CONTROL/MERMIN/RETARD",
                    visible_when=[VisibleWhen(key="occupations", value="mermin")],
                ),
            ],
        ),
        Section(
            id="wavefunction_dynamics",
            label="Wave-function dynamics",
            advanced=True,
            parameters=[
                ParameterSpec(
                    key="psi_friction",
                    label="Friction (start)",
                    type="number",
                    default=0.05,
                    minimum=0,
                    maximum=1,
                    backend_path="CONTROL/PSIDYN/FRIC",
                ),
                ParameterSpec(
                    key="psi_auto",
                    label="Automatic friction (autopilot)",
                    type="boolean",
                    default=True,
                    backend_path="CONTROL/PSIDYN/AUTO",
                ),
                ParameterSpec(
                    key="psi_auto_fric_minus",
                    label="FRIC(-)",
                    type="number",
                    default=0.3,
                    minimum=0,
                    backend_path="CONTROL/PSIDYN/AUTO/FRIC(-)",
                    visible_when=[VisibleWhen(key="psi_auto", op="truthy")],
                ),
                ParameterSpec(
                    key="psi_auto_fact_minus",
                    label="FACT(-)",
                    type="number",
                    default=0.97,
                    minimum=0,
                    backend_path="CONTROL/PSIDYN/AUTO/FACT(-)",
                    visible_when=[VisibleWhen(key="psi_auto", op="truthy")],
                ),
                ParameterSpec(
                    key="psi_auto_fric_plus",
                    label="FRIC(+)",
                    type="number",
                    default=0.3,
                    minimum=0,
                    backend_path="CONTROL/PSIDYN/AUTO/FRIC(+)",
                    visible_when=[VisibleWhen(key="psi_auto", op="truthy")],
                ),
                ParameterSpec(
                    key="psi_auto_minfric",
                    label="Minimum friction",
                    type="number",
                    default=0.01,
                    minimum=0,
                    backend_path="CONTROL/PSIDYN/AUTO/MINFRIC",
                    visible_when=[VisibleWhen(key="psi_auto", op="truthy")],
                ),
                ParameterSpec(
                    key="safeortho",
                    label="Strict orthogonalization (SAFEORTHO)",
                    type="boolean",
                    default=True,
                    backend_path="CONTROL/PSIDYN/SAFEORTHO",
                ),
            ],
        ),
        Section(
            id="atomic_dynamics",
            label="Atomic dynamics",
            parameters=[
                ParameterSpec(
                    key="atom_friction",
                    label="Atomic friction",
                    type="number",
                    default=0.1,
                    minimum=0,
                    maximum=1,
                    backend_path="CONTROL/RDYN/FRIC",
                    visible_when=[VisibleWhen(key="task", value="relax")],
                ),
                ParameterSpec(
                    key="atom_auto",
                    label="Automatic atomic friction",
                    type="boolean",
                    default=True,
                    backend_path="CONTROL/RDYN/AUTO",
                    visible_when=[VisibleWhen(key="task", value="relax")],
                ),
                ParameterSpec(
                    key="temperature",
                    label="Temperature",
                    type="number",
                    default=300.0,
                    minimum=0,
                    unit=Unit.KELVIN,
                    backend_path="CONTROL/RDYN/THERMOSTAT/T[K]",
                    visible_when=[VisibleWhen(key="task", value="md")],
                ),
                ParameterSpec(
                    key="thermostat",
                    label="Nosé thermostat (atoms)",
                    type="boolean",
                    default=True,
                    backend_path="CONTROL/RDYN/THERMOSTAT",
                    visible_when=[VisibleWhen(key="task", value="md")],
                ),
                ParameterSpec(
                    key="thermostat_freq",
                    label="Thermostat frequency (THz)",
                    type="number",
                    default=10.0,
                    minimum=0,
                    exclusive_minimum=True,
                    advanced=True,
                    backend_path="CONTROL/RDYN/THERMOSTAT/FREQ[THZ]",
                    visible_when=[
                        VisibleWhen(key="task", value="md"),
                        VisibleWhen(key="thermostat", op="truthy"),
                    ],
                ),
                ParameterSpec(
                    key="psi_thermostat",
                    label="Nosé thermostat (wave functions)",
                    type="boolean",
                    default=True,
                    advanced=True,
                    backend_path="CONTROL/PSIDYN/THERMOSTAT",
                    visible_when=[VisibleWhen(key="task", value="md")],
                    help="Keeps the fictitious electron dynamics cold during MD (tutorial ch. 5).",
                ),
                ParameterSpec(
                    key="random_velocities",
                    label="Initial random velocities (K)",
                    type="number",
                    default=0.0,
                    minimum=0,
                    advanced=True,
                    backend_path="CONTROL/RDYN/RANDOM[K]",
                    visible_when=[VisibleWhen(key="task", value="md")],
                ),
                ParameterSpec(
                    key="force_steps",
                    label="Damped atomic steps for forces",
                    type="integer",
                    default=5,
                    minimum=1,
                    advanced=True,
                    visible_when=[VisibleWhen(key="task", value="forces")],
                    help="Steps with friction 1 (steepest descent) after which forces are read from the last ATOMLIST report.",
                ),
            ],
        ),
        Section(
            id="cell",
            label="Periodicity and k-points",
            parameters=[
                ParameterSpec(
                    key="box_margin",
                    label="Vacuum margin for molecules",
                    type="number",
                    default=4.0,
                    minimum=0.5,
                    unit=Unit.ANGSTROM,
                    backend_path="STRUCTURE/LATTICE/T",
                    help="Non-periodic structures are placed in an orthorhombic box: extent + 2 × margin.",
                ),
                ParameterSpec(
                    key="isolate",
                    label="Electrostatic decoupling of periodic images (!ISOLATE)",
                    type="boolean",
                    default=True,
                    backend_path="STRUCTURE/ISOLATE",
                    help="Recommended for molecules; applied only to non-periodic structures.",
                ),
                ParameterSpec(
                    key="kpoint_mode",
                    label="k-point sampling",
                    type="enum",
                    default="density",
                    choices=[
                        Choice(value="gamma", label="Γ point only"),
                        Choice(value="density", label="Automatic from real-space length R"),
                        Choice(value="grid", label="Explicit grid (DIV)"),
                    ],
                    backend_path="STRUCTURE/KPOINTS",
                ),
                ParameterSpec(
                    key="kpoint_r",
                    label="k-point density R",
                    type="number",
                    default=12.0,
                    minimum=0,
                    exclusive_minimum=True,
                    unit=Unit.BOHR,
                    backend_path="STRUCTURE/KPOINTS/R",
                    help="Δk = 2π/R; larger R → denser mesh (tutorial uses 30 for solids).",
                    visible_when=[VisibleWhen(key="kpoint_mode", value="density")],
                ),
                ParameterSpec(
                    key="kpoint_div",
                    label="k-point grid",
                    type="vector",
                    length=3,
                    integer_vector=True,
                    default=[2, 2, 2],
                    minimum=1,
                    backend_path="STRUCTURE/KPOINTS/DIV",
                    visible_when=[VisibleWhen(key="kpoint_mode", value="grid")],
                ),
            ],
        ),
        Section(
            id="setups",
            label="Species and setups",
            advanced=True,
            parameters=[
                ParameterSpec(
                    key="setup_type",
                    label="Setup family",
                    type="enum",
                    default=".75_6.0",
                    choices=SETUP_CHOICES,
                    backend_path="STRUCTURE/SPECIES/ID",
                ),
                ParameterSpec(
                    key="lrhox",
                    label="LRHOX",
                    type="integer",
                    default=2,
                    minimum=0,
                    backend_path="STRUCTURE/SPECIES/LRHOX",
                ),
                ParameterSpec(
                    key="rad_rcov",
                    label="RAD/RCOV",
                    type="number",
                    default=1.4,
                    minimum=0,
                    exclusive_minimum=True,
                    backend_path="STRUCTURE/SPECIES/RAD/RCOV",
                ),
                ParameterSpec(
                    key="npro_overrides",
                    label="NPRO overrides",
                    type="string",
                    default="",
                    backend_path="STRUCTURE/SPECIES/NPRO",
                    help="e.g. 'Fe: 2 2 2; O: 2 2 1' — projectors per angular momentum; default 1 1 for H/He, 2 2 1 otherwise.",
                ),
                ParameterSpec(
                    key="hydrogen_mass",
                    label="Hydrogen mass (u)",
                    type="number",
                    default=0.0,
                    minimum=0,
                    backend_path="STRUCTURE/SPECIES/M",
                    help="0 = natural mass. The course uses 2 u to allow larger time steps.",
                ),
            ],
        ),
        Section(
            id="output",
            label="Output and analysis",
            parameters=[
                ParameterSpec(
                    key="write_density",
                    label="Electron density (cube)",
                    type="boolean",
                    default=False,
                    backend_path="CONTROL/ANALYSE/DENSITY",
                ),
                ParameterSpec(
                    key="write_spin_density",
                    label="Spin density (cube)",
                    type="boolean",
                    default=False,
                    backend_path="CONTROL/ANALYSE/DENSITY",
                    visible_when=[VisibleWhen(key="spin_polarized", op="truthy")],
                ),
                ParameterSpec(
                    key="orbital_bands",
                    label="Orbitals to export (band indices)",
                    type="string",
                    default="",
                    backend_path="CONTROL/ANALYSE/WAVE",
                    help="Space-separated band indices, e.g. '3 4 5' (1-based, k-point 1, spin 1). Each becomes a cube file.",
                ),
                ParameterSpec(
                    key="grid_spacing",
                    label="Grid spacing for cubes",
                    type="number",
                    default=0.4,
                    minimum=0.05,
                    unit=Unit.BOHR,
                    advanced=True,
                    backend_path="CONTROL/ANALYSE/DENSITY/DR",
                ),
                ParameterSpec(
                    key="energy_trajectory",
                    label="Energy trajectory (_e.tra)",
                    type="boolean",
                    default=True,
                    advanced=True,
                    backend_path="CONTROL/ANALYSE/TRA/E",
                ),
            ],
        ),
    ],
)

PRESETS = [
    Preset(
        id="molecule_single_point",
        name="Molecule: wave-function optimization",
        schema_id="cppaw",
        description="Tutorial ch. 2.7: converge the electrons of an isolated molecule.",
        values={"task": "single_point", "nstep": 300, "epwpsi": 30.0, "cdual": 2.0},
    ),
    Preset(
        id="molecule_relax",
        name="Molecule: geometry optimization",
        schema_id="cppaw",
        description="Tutorial ch. 2.8: damped atomic dynamics with autopilot.",
        values={"task": "relax", "nstep": 1000, "atom_friction": 0.1, "hydrogen_mass": 2.0},
    ),
    Preset(
        id="molecule_md",
        name="Molecule: molecular dynamics (Nosé)",
        schema_id="cppaw",
        description="Tutorial ch. 5: MD with thermostats for atoms and wave functions.",
        values={
            "task": "md",
            "start": "restart",
            "nstep": 2000,
            "temperature": 300.0,
            "thermostat": True,
            "psi_thermostat": True,
            "hydrogen_mass": 2.0,
            "nwrite": 100,
        },
    ),
    Preset(
        id="solid_insulator",
        name="Solid (insulator): single point",
        schema_id="cppaw",
        description="Tutorial ch. 6 silicon: k-point density R=30.",
        values={
            "task": "single_point",
            "kpoint_mode": "density",
            "kpoint_r": 30.0,
            "empty_bands": 5,
            "isolate": False,
        },
    ),
    Preset(
        id="solid_metal",
        name="Solid (metal): Mermin occupations",
        schema_id="cppaw",
        description="Tutorial ch. 6.4 aluminium: fractional occupations, SAFEORTHO=F.",
        values={
            "task": "single_point",
            "occupations": "mermin",
            "electron_temperature": 0.0,
            "kpoint_mode": "density",
            "kpoint_r": 30.0,
            "empty_bands": 8,
            "safeortho": False,
            "isolate": False,
        },
    ),
    Preset(
        id="ferromagnet",
        name="Ferromagnet (spin polarized, Mermin)",
        schema_id="cppaw",
        description="Tutorial ch. 7.2 iron.",
        values={
            "task": "single_point",
            "occupations": "mermin",
            "spin_polarized": True,
            "total_spin": 2.0,
            "kpoint_mode": "density",
            "kpoint_r": 30.0,
            "empty_bands": 10,
            "safeortho": False,
            "isolate": False,
            "write_spin_density": True,
        },
    ),
]
