"""Generate frontend/src/model/elements.ts from ASE's and Open Babel's periodic table data.

Colors: Jmol CPK scheme (ase.data.colors.jmol_colors), covalent radii: ase.data.covalent_radii
(Cordero 2008), masses: ase.data.atomic_masses.

**Van der Waals radii come from Open Babel, not from ASE.** `ase.data.vdw_radii` is Bondi's set,
which has no value for 50 of the 104 elements -- every 3d and 4d transition metal among them, so
iron and nickel had none. Avogadro 1 reads `OpenBabel::etab.GetVdwRad`, which covers all of them,
and matching what Avogadro draws is the point of this column: it is the radius basis its
ball-and-stick engine uses by default, as well as the space-filling radius. The one visible
difference from Bondi is hydrogen, 1.10 A instead of 1.20.

Run: .venv/bin/python scripts/gen_element_data.py
"""

from __future__ import annotations

import math
from pathlib import Path

from ase.data import atomic_masses, atomic_names, chemical_symbols, covalent_radii
from ase.data.colors import jmol_colors
from openbabel import openbabel as ob

out = Path(__file__).resolve().parent.parent / "frontend/src/model/elements.ts"
lines = [
    "// GENERATED by scripts/gen_element_data.py from ASE data tables. Do not edit by hand.",
    "// Colors: Jmol CPK; covalent radii: Cordero et al. 2008; masses: IUPAC.",
    "// vdW radii: Open Babel's table, which is the one Avogadro 1's ball-and-stick engine reads",
    "// and which -- unlike ASE's Bondi set -- has a value for every element.",
    "export interface ElementData {",
    "  symbol: string;",
    "  name: string;",
    "  number: number;",
    "  mass: number;",
    "  covalentRadius: number; // Å",
    "  vdwRadius: number; // Å (NaN when unknown)",
    "  color: [number, number, number]; // 0..1 RGB",
    "}",
    "",
    "export const ELEMENTS: readonly ElementData[] = [",
]
for z, sym in enumerate(chemical_symbols):
    if z > 103:
        break
    r, g, b = (round(float(c), 3) for c in jmol_colors[z])
    vdw = float(ob.GetVdwRad(z)) if z > 0 else math.nan
    vdw_s = "NaN" if math.isnan(vdw) or vdw <= 0 else f"{vdw:.2f}"
    lines.append(
        f"  {{ symbol: '{sym}', name: '{atomic_names[z] or sym}', number: {z}, "
        f"mass: {float(atomic_masses[z]):.4f}, "
        f"covalentRadius: {float(covalent_radii[z]):.2f}, vdwRadius: {vdw_s}, color: [{r}, {g}, {b}] }},"
    )
lines += [
    "];",
    "",
    "export const ELEMENT_BY_SYMBOL: ReadonlyMap<string, ElementData> = new Map(",
    "  ELEMENTS.map((e) => [e.symbol, e]),",
    ");",
    "",
    "export function elementBySymbol(symbol: string): ElementData {",
    "  return ELEMENT_BY_SYMBOL.get(symbol) ?? ELEMENTS[0]!;",
    "}",
    "",
]
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(chemical_symbols[:104])} elements)")
