"""Generate frontend/src/model/elements.ts from ASE's periodic table data.

Colors: Jmol CPK scheme (ase.data.colors.jmol_colors), radii: covalent (Cordero 2008) and
van der Waals (ase.data.vdw_radii, Bondi/Alvarez), masses: ase.data.atomic_masses.
Run: .venv/bin/python scripts/gen_element_data.py
"""

from __future__ import annotations

import math
from pathlib import Path

from ase.data import atomic_masses, atomic_names, chemical_symbols, covalent_radii, vdw_radii
from ase.data.colors import jmol_colors

out = Path(__file__).resolve().parent.parent / "frontend/src/model/elements.ts"
lines = [
    "// GENERATED by scripts/gen_element_data.py from ASE data tables. Do not edit by hand.",
    "// Colors: Jmol CPK; covalent radii: Cordero et al. 2008; vdW radii: Bondi/Alvarez; masses: IUPAC.",
    "export interface ElementData {",
    "  symbol: string;",
    "  name: string;",
    "  number: number;",
    "  mass: number;",
    "  covalentRadius: number; // Å",
    "  vdwRadius: number; // Å (NaN when unknown)",
    "  color: [number, number, number]; // 0..1 RGB",
    "}",
    "",
    "export const ELEMENTS: readonly ElementData[] = [",
]
for z, sym in enumerate(chemical_symbols):
    if z > 103:
        break
    r, g, b = (round(float(c), 3) for c in jmol_colors[z])
    vdw = float(vdw_radii[z]) if z < len(vdw_radii) else math.nan
    vdw_s = "NaN" if math.isnan(vdw) else f"{vdw:.2f}"
    lines.append(
        f"  {{ symbol: '{sym}', name: '{atomic_names[z] or sym}', number: {z}, "
        f"mass: {float(atomic_masses[z]):.4f}, "
        f"covalentRadius: {float(covalent_radii[z]):.2f}, vdwRadius: {vdw_s}, color: [{r}, {g}, {b}] }},"
    )
lines += [
    "];",
    "",
    "export const ELEMENT_BY_SYMBOL: ReadonlyMap<string, ElementData> = new Map(",
    "  ELEMENTS.map((e) => [e.symbol, e]),",
    ");",
    "",
    "export function elementBySymbol(symbol: string): ElementData {",
    "  return ELEMENT_BY_SYMBOL.get(symbol) ?? ELEMENTS[0]!;",
    "}",
    "",
]
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(chemical_symbols[:104])} elements)")
