/**
 * @perf -- renderer performance harness. Excluded from the normal e2e suite; run it with
 *
 *     ATOMSCOPE_PERF=1 pnpm exec playwright test
 *
 * (see playwright.config.ts). It measures, inside the page with `performance.now()`:
 *
 *   first render   time from clicking a structure in the project panel until the frame that
 *                  first shows the complete atom mesh (renderer.onFrame + scene inspection)
 *   orbit FPS      frames drawn per second while `CameraController.orbit()` runs in a
 *                  requestAnimationFrame loop for a fixed wall-clock window
 *   isosurface     time from "Add surface" until the isosurface mesh has vertices
 *
 * Results are appended to ../.scratch/bench/frontend-perf.{json,md}. The only production-code
 * instrumentation used is `Renderer.frameCount` (one integer increment per frame) and
 * `Renderer.onFrame` (a null check per frame); `window.__atomscopeRenderer` exists in dev only.
 */
import { expect, test, type Page } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Renderer } from '../src/renderer/Renderer';

/** The dev-only handle installed by `Renderer` (see its `declare global`). */
type PerfWindow = Window & { __atomscopeRenderer?: Renderer };

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(HERE, '../../.scratch/bench');
const BASE = process.env['PLAYWRIGHT_BASE_URL'] ?? 'http://127.0.0.1:5173';
const ORBIT_MS = 4000;
const MIN_ORBIT_FRAMES = 5;
const ORBIT_CAP_MS = 120_000;

const SIZES: { label: string; n: number }[] = [
  { label: '1e3', n: 1_000 },
  { label: '1e4', n: 10_000 },
  { label: '1e5', n: 100_000 },
];

interface Row {
  case: string;
  value: number;
  unit: string;
  note: string;
}
const rows: Row[] = [];

function record(row: Row): void {
  rows.push(row);
  console.log(`  ${row.case}: ${row.value.toFixed(1)} ${row.unit} (${row.note})`);
}

test.afterAll(() => {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'frontend-perf.json'), JSON.stringify(rows, null, 2) + '\n');
  const md = [
    '### frontend rendering (headless Chromium, SwiftShader software WebGL)',
    '',
    '| case | value | unit | note |',
    '| --- | ---: | --- | --- |',
    ...rows.map((r) => `| \`${r.case}\` | ${r.value.toFixed(1)} | ${r.unit} | ${r.note} |`),
    '',
  ].join('\n');
  writeFileSync(join(OUT_DIR, 'frontend-perf.md'), md);
});

/** A carbon/nitrogen/oxygen lattice with roughly one bond per atom (molecular-like topology). */
function makeStructure(id: string, name: string, n: number): Record<string, unknown> {
  const side = Math.ceil(Math.cbrt(n));
  const atoms: { element: string; position: [number, number, number] }[] = [];
  const bonds: { a: number; b: number; order: number; aromatic: boolean }[] = [];
  for (let i = 0; i < n; i++) {
    const x = i % side;
    const y = Math.floor(i / side) % side;
    const z = Math.floor(i / (side * side));
    const element = i % 11 === 0 ? 'N' : i % 7 === 0 ? 'O' : 'C';
    atoms.push({ element, position: [x * 1.6, y * 1.6, z * 1.6] });
    if (x > 0) bonds.push({ a: i - 1, b: i, order: 1, aromatic: false });
  }
  return { id, name, atoms, bonds };
}

/** A 128^3 Gaussian-blob cube file, written once into the test output directory. */
function writeCube(path: string, n: number): void {
  const step = 0.25 / 0.529177210903; // 0.25 Å per voxel, expressed in Bohr
  const head = [
    'perf grid',
    'generated by perf.spec.ts',
    '    1     0.000000     0.000000     0.000000',
    `${String(n).padStart(5)} ${step.toFixed(6).padStart(12)} ${(0).toFixed(6).padStart(12)} ${(0).toFixed(6).padStart(12)}`,
    `${String(n).padStart(5)} ${(0).toFixed(6).padStart(12)} ${step.toFixed(6).padStart(12)} ${(0).toFixed(6).padStart(12)}`,
    `${String(n).padStart(5)} ${(0).toFixed(6).padStart(12)} ${(0).toFixed(6).padStart(12)} ${step.toFixed(6).padStart(12)}`,
    `    8     8.000000    ${(n * step * 0.5).toFixed(6)}    ${(n * step * 0.5).toFixed(6)}    ${(n * step * 0.5).toFixed(6)}`,
  ];
  const parts: string[] = [head.join('\n'), '\n'];
  const line: string[] = [];
  for (let i = 0; i < n; i++) {
    const xi = (2 * i) / (n - 1) - 1;
    for (let j = 0; j < n; j++) {
      const yj = (2 * j) / (n - 1) - 1;
      for (let k = 0; k < n; k++) {
        const zk = (2 * k) / (n - 1) - 1;
        let v = 0;
        for (const c of [-0.5, -0.15, 0.2, 0.55]) {
          v += Math.exp(-12 * ((xi - c) ** 2 + (yj - c * 0.4) ** 2 + (zk + c * 0.7) ** 2));
        }
        line.push(v.toExponential(5).toUpperCase().padStart(13));
        if (line.length === 6) {
          parts.push(line.join(' ') + '\n');
          line.length = 0;
        }
      }
    }
  }
  if (line.length) parts.push(line.join(' ') + '\n');
  writeFileSync(path, parts.join(''));
}

/** Wire a per-frame hook that stops at the first frame showing `expected` atom instances. */
async function armFirstRender(page: Page, expected: number): Promise<void> {
  await page.evaluate((count) => {
    const w = window as unknown as { __perfT0?: number; __perfFirst?: number };
    const r = (window as unknown as PerfWindow).__atomscopeRenderer;
    if (!r) throw new Error('renderer handle missing (is the dev server in production mode?)');
    w.__perfFirst = undefined;
    r.onFrame = () => {
      if (w.__perfT0 === undefined || w.__perfFirst !== undefined) return;
      let found = false;
      r.scene.traverse((o) => {
        const mesh = o as unknown as { isInstancedMesh?: boolean; count?: number };
        if (mesh.isInstancedMesh && mesh.count === count) found = true;
      });
      if (found) w.__perfFirst = performance.now() - w.__perfT0;
    };
    w.__perfT0 = performance.now();
  }, expected);
}

async function firstRenderResult(page: Page): Promise<number> {
  await expect
    .poll(
      () =>
        page.evaluate(() => (window as unknown as { __perfFirst?: number }).__perfFirst ?? -1),
      { timeout: 180_000, intervals: [100] },
    )
    .toBeGreaterThan(0);
  const ms = await page.evaluate(() => {
    const w = window as unknown as { __perfFirst?: number };
    const r = (window as unknown as PerfWindow).__atomscopeRenderer;
    if (r) r.onFrame = null;
    return w.__perfFirst ?? -1;
  });
  return ms;
}

/**
 * Orbit the camera in a rAF loop and return frames drawn, wall time and the resulting rate.
 * The window runs at least `ms` and until at least `MIN_ORBIT_FRAMES` frames are drawn (capped),
 * so a system where one frame takes seconds still yields a meaningful number.
 */
async function orbitFps(
  page: Page,
  ms: number,
): Promise<{ fps: number; frames: number; elapsed: number }> {
  return page.evaluate(
    async ([duration, minFrames, cap]) => {
      const r = (window as unknown as PerfWindow).__atomscopeRenderer;
      if (!r) throw new Error('renderer handle missing');
      const start = performance.now();
      const frames0 = r.frameCount;
      await new Promise<void>((done) => {
        const tick = (): void => {
          r.controller.orbit(4, 2);
          const elapsed = performance.now() - start;
          const frames = r.frameCount - frames0;
          if (elapsed >= cap! || (elapsed >= duration! && frames >= minFrames!)) done();
          else requestAnimationFrame(tick);
        };
        requestAnimationFrame(tick);
      });
      const elapsed = performance.now() - start;
      const frames = r.frameCount - frames0;
      return { fps: (frames * 1000) / elapsed, frames, elapsed };
    },
    [ms, MIN_ORBIT_FRAMES, ORBIT_CAP_MS] as const,
  );
}

/** Duration of the `/api/structures/<id>` fetch that the click triggered, in ms. */
async function fetchMs(page: Page, structureId: string): Promise<number> {
  return page.evaluate((id) => {
    const entries = performance.getEntriesByType('resource');
    const hit = entries.filter((e) => e.name.includes(`/api/structures/${id}`)).pop();
    return hit ? hit.duration : -1;
  }, structureId);
}

test.describe('@perf renderer', () => {
  test.describe.configure({ timeout: 900_000 });

  test('structure first render and orbit frame rate', async ({ page, request }) => {
    const dir = test.info().outputPath('project');
    await request.post(`${BASE}/api/project/close`);
    const created = await request.post(`${BASE}/api/project/create`, {
      data: { path: join(dir, 'p'), name: 'perf' },
    });
    expect(created.ok()).toBeTruthy();
    for (const { label, n } of SIZES) {
      const s = makeStructure(`perf${label.replace('e', '')}`, `perf-${label}`, n);
      const put = await request.put(`${BASE}/api/structures/${String(s['id'])}`, {
        data: s,
        timeout: 300_000,
      });
      expect(put.ok(), `PUT perf-${label}`).toBeTruthy();
    }

    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    await page.goto('/');
    await expect(page.locator('.app-statusbar')).toContainText('H2O');

    for (const { label, n } of SIZES) {
      const id = `perf${label.replace('e', '')}`;
      const bonds = n - Math.ceil(Math.cbrt(n)) ** 2;
      const item = page.getByRole('button', { name: new RegExp(`perf-${label}\\b`) });
      await expect(item).toBeVisible({ timeout: 30_000 });
      await armFirstRender(page, n);
      await item.click();
      const total = await firstRenderResult(page);
      const fetched = await fetchMs(page, id);
      const shape = `${n.toLocaleString('en-US')} atoms, ${bonds.toLocaleString('en-US')} bonds`;
      record({
        case: `structure.open_total.${label}`,
        value: total,
        unit: 'ms',
        note: `${shape}, click -> first complete frame (fetch + normalise + build + draw)`,
      });
      record({
        case: `structure.api_fetch.${label}`,
        value: fetched,
        unit: 'ms',
        note: `${shape}, GET /api/structures/${id} as seen by the browser`,
      });
      record({
        case: `structure.first_render.${label}`,
        value: total - Math.max(fetched, 0),
        unit: 'ms',
        note: `${shape}, open_total minus the API fetch: normalise + layer rebuild + first draw`,
      });
      const orbit = await orbitFps(page, ORBIT_MS);
      expect(orbit.frames, `no frames drawn while orbiting perf-${label}`).toBeGreaterThan(0);
      record({
        case: `structure.orbit_fps.${label}`,
        value: orbit.fps,
        unit: 'fps',
        note: `${shape}, ${orbit.frames} frames in ${(orbit.elapsed / 1000).toFixed(1)} s of continuous orbit`,
      });
    }
    expect(errors).toEqual([]);
  });

  test('isosurface from a 128^3 grid', async ({ page, request }) => {
    const dir = test.info().outputPath('grid');
    mkdirSync(dir, { recursive: true });
    const cube = join(dir, 'perf-128.cube');
    const t0 = Date.now();
    writeCube(cube, 128);
    console.log(`  (cube fixture written in ${((Date.now() - t0) / 1000).toFixed(1)} s)`);

    await request.post(`${BASE}/api/project/close`);
    const created = await request.post(`${BASE}/api/project/create`, {
      data: { path: join(dir, 'p'), name: 'perf-grid' },
    });
    expect(created.ok()).toBeTruthy();

    await page.goto('/');
    await expect(page.locator('.app-statusbar')).toContainText('H2O');
    await page.getByRole('tab', { name: 'Surfaces' }).click();
    await page.getByLabel('Import cube').fill(cube);
    const importStart = Date.now();
    await page.getByRole('button', { name: 'Import' }).click();
    await expect(page.getByText('128 × 128 × 128')).toBeVisible({ timeout: 300_000 });
    record({
      case: 'isosurface.grid_import.128',
      value: Date.now() - importStart,
      unit: 'ms',
      note: 'backend cube parse + float32 transfer of 2,097,152 voxels',
    });

    // arm the hook, then ask for a surface; stop at the first frame that has surface geometry
    await page.evaluate(() => {
      const w = window as unknown as { __perfT0?: number; __perfFirst?: number };
      const r = (window as unknown as PerfWindow).__atomscopeRenderer;
      if (!r) throw new Error('renderer handle missing');
      w.__perfFirst = undefined;
      r.onFrame = () => {
        if (w.__perfT0 === undefined || w.__perfFirst !== undefined) return;
        let vertices = 0;
        r.scene.traverse((o) => {
          const m = o as unknown as {
            isMesh?: boolean;
            isInstancedMesh?: boolean;
            geometry?: { attributes?: { position?: { count?: number } } };
          };
          if (m.isMesh && !m.isInstancedMesh) vertices += m.geometry?.attributes?.position?.count ?? 0;
        });
        if (vertices > 0) w.__perfFirst = performance.now() - w.__perfT0;
      };
      w.__perfT0 = performance.now();
    });
    await page.getByRole('button', { name: 'Add surface' }).click();
    const ms = await firstRenderResult(page);
    record({
      case: 'isosurface.first_mesh.128',
      value: ms,
      unit: 'ms',
      note: 'Add surface -> first frame with mesh (worker marching cubes at step 1)',
    });
  });
});
