"""The hands-on course as Atomscope inputs.

Each entry is one exercise from the CP-PAW hands-on course tutorial (Blöchl, Schade, ten Brink,
2019), given as the structure and the schema values that reproduce it. The course's own decks are
read as a specification: what is written here is parameters, and the deck is generated by our
CP-PAW plugin from them, so the example library exercises the same path a person using the
application does. `docs/course/inventory.md` says why the document itself is not in the repository.

Chapter numbers refer to that tutorial.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ase import Atoms
from atomscope.ase_bridge import from_atoms
from atomscope.calculations.sweeps import SweepPointSpec, SweepSpec
from atomscope.model import Structure


@dataclass(frozen=True)
class Exercise:
    """One course exercise, ready to run."""

    id: str
    chapter: str
    title: str
    """What the exercise is for, in our words."""
    structure: Structure
    values: dict[str, Any]
    """Schema values that differ from the plugin's defaults, or that the course states outright."""
    shows: str
    """What the course asks you to look at, and therefore what the example has to visualize."""
    analysis: tuple[tuple[str, dict[str, Any]], ...] = ()
    """Analysis tools to run once the calculation finishes: ("dos" | "bands" | "orbitals", opts)."""
    continues: str | None = None
    """An exercise whose restart file this one carries on from, as the course's chapters do."""
    notes: tuple[str, ...] = field(default_factory=tuple)
    """Where our deck departs from the course's, and why."""


def _water() -> Structure:
    """Chapter 2.5: one water molecule in a 12 Å fcc cell, the course's own coordinates.

    The cell is written as the three face-centred vectors of a cube of side 12 Å, which puts the
    nearest periodic image 7 Å away -- the course explains that the fcc cell is the best shape for
    an isolated molecule because it packs spheres most tightly for a given image separation.
    """
    return from_atoms(
        Atoms(
            "OH2",
            positions=[(0.0, 0.0, 0.0), (1.05, 0.0, 0.0), (0.0, 1.05, 0.0)],
            cell=[(0.0, 6.0, 6.0), (6.0, 0.0, 6.0), (6.0, 6.0, 0.0)],
            pbc=True,
        ),
        name="water",
    )


#: Values common to the course's early chapters: PBE, 30 Ry / dual 2, and the friction schedule
#: chapter 2.6 spells out. Our defaults already agree on the functional and the cutoffs.
COURSE_WAVEFUNCTION = {
    "xc": 10,
    "epwpsi": 30.0,
    "cdual": 2.0,
    "psi_friction": 0.01,
    "psi_auto": True,
    "psi_auto_fric_minus": 0.3,
    "psi_auto_fact_minus": 0.97,
    "psi_auto_fric_plus": 0.3,
    "psi_auto_minfric": 0.02,
    "lrhox": 4,
    "npro_overrides": "H: 1 0 0; O: 2 2 1",
    "setup_type": ".75_6.0",
    "isolate": "always",
    "kpoint_mode": "gamma",
}

EXERCISES: tuple[Exercise, ...] = (
    Exercise(
        id="water-wavefunction",
        chapter="2.7",
        title="Optimize the wave functions of a water molecule",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "scratch",
            "nstep": 200,
            "empty_bands": 5,
            "energy_trajectory": True,
        },
        shows="the total energy falling to a constant over the iterations, and the HOMO-LUMO gap",
        notes=(
            (
                "The course asks for at least one empty state so the gap can be read off, and"
                " notes that EMPTY=5 becomes six states because two real wave functions are"
                " packed into one complex one. We pass the 5 it asks for and let CP-PAW round,"
                " as it does for the course."
            ),
            (
                "The course quotes an absolute gap of 5.4665 eV. The binaries installed here give"
                " 5.3843 eV -- and so does the course's own deck, typed out and run directly, so"
                " the difference is the code or the setups this machine has, not our input."
            ),
        ),
    ),
)


def _water_relaxation() -> Exercise:
    """Chapter 2.8: relax the geometry once the wave functions are converged.

    The course continues from the restart file the previous run left, with lower wave-function
    friction and a friction on the atoms that decays while the energy keeps falling.
    """
    return Exercise(
        id="water-relax",
        chapter="2.8",
        title="Relax the atomic positions of water",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "relax",
            "start": "restart",
            "nstep": 2000,
            "empty_bands": 5,
            "psi_auto_fric_minus": 0.05,
            "psi_auto_fric_plus": 0.2,
            "atom_friction": 0.0,
            "atom_auto": True,
            "atom_auto_fric_minus": 0.0,
            "atom_auto_fact_minus": 0.9,
            "atom_auto_fric_plus": 0.01,
        },
        shows="the O-H bond length and the H-O-H angle the relaxation settles on",
        continues="water-wavefunction",
        notes=(
            (
                "The course starts this from the restart file the ch. 2.7 run left behind, so the"
                " example does too: it is the same working directory, with START=F."
            ),
            (
                "Result: 0.9815 A and 105.07 degrees, against the 0.981 A and 105.2 degrees the"
                " course reports for the same calculation. Experiment is 0.9572 A and 104.474."
            ),
        ),
    )


EXERCISES = (*EXERCISES, _water_relaxation())


def _water_orbitals() -> Exercise:
    """Chapter 3: the molecular orbitals, the electron density, and the density of states.

    The course exports the wave functions of a converged calculation as grids and looks at them
    as isosurfaces, then runs `paw_dos` over the same calculation for the total and projected
    density of states. Both come off the relaxed geometry of ch. 2.8.
    """
    return Exercise(
        id="water-orbitals",
        chapter="3.3, 3.5",
        title="Molecular orbitals, density and DOS of water",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "restart",
            "nstep": 200,
            "empty_bands": 5,
            "write_density": True,
            "grid_spacing": 0.25,
        },
        shows=(
            "isosurfaces of the four occupied orbitals and the first empty one, the electron"
            " density, and the total and projected density of states"
        ),
        continues="water-relax",
        analysis=(
            (
                "orbitals",
                {
                    "orbitals": [
                        {"band": b, "kpoint": 1, "spin": 1} for b in range(1, 7)
                    ]
                },
            ),
            # 2000 K in the course's !GRID BROADENING[K]; k_B T at 2000 K is 0.172 eV
            (
                "dos",
                {
                    "broadening_ev": 0.172,
                    "de_ev": 0.01,
                    "projection": "atom",
                    # ch. 3.5's own COOP: the oxygen's sp3 lobe pointing at a hydrogen against
                    # that hydrogen's s orbital. Positive where they bond, negative where they
                    # do not.
                    "coops": [
                        {
                            "id": "o-h",
                            "label": "O sp3 - H s",
                            "first": {"atom": 0, "type": "SP3", "toward": 1},
                            "second": {"atom": 1, "type": "S", "toward": 0},
                        }
                    ],
                    # ch. 4.7.4 is about this: an orbital in a frame of its own rather than the
                    # cell's, which for a lone pair is the only frame that means anything
                    "orbital_weights": [
                        {
                            "id": "o-sp3",
                            "label": "O sp3 toward H",
                            "orbitals": [{"atom": 0, "type": "SP3", "toward": 1}],
                        }
                    ],
                },
            ),
        ),
        notes=(
            (
                "The course's .dcntl asks for the total DOS, oxygen s and p separately, and the"
                " two hydrogens together, then a COOP between the oxygen sp3 and the hydrogen s."
                " We write the total and a projection per atom and angular momentum, which covers"
                " its first four weights, plus that COOP and one local-frame orbital of the kind"
                " ch. 4.7.4 is about."
            ),
        ),
    )


EXERCISES = (*EXERCISES, _water_orbitals())


#: The geometry our own ch. 2.8 run settled on: 0.9815 A, 105.07 degrees. The course's ch. 8.5
#: says to sweep the cell around "the relaxed structure from section 2.8", so this is it, written
#: down rather than read out of a run directory that may not exist.
RELAXED_WATER = (
    ("O", (0.0144, 0.0144, 0.0)),
    ("H", (0.9875, -0.1143, 0.0)),
    ("H", (-0.1143, 0.9875, 0.0)),
)


def fcc_water(lattice_parameter: float) -> Structure:
    """Relaxed water in a face-centred cell of cube edge ``lattice_parameter`` (A)."""
    half = lattice_parameter / 2.0
    return from_atoms(
        Atoms(
            "".join(e for e, _ in RELAXED_WATER),
            positions=[p for _, p in RELAXED_WATER],
            cell=[(0.0, half, half), (half, 0.0, half), (half, half, 0.0)],
            pbc=True,
        ),
        name=f"water in a {lattice_parameter:g} A fcc cell",
    )


@dataclass(frozen=True)
class SweepExercise:
    """A course exercise that is several runs and one curve."""

    id: str
    chapter: str
    title: str
    structure: Structure
    """The reference structure; points may bring their own."""
    spec: SweepSpec
    shows: str
    continues: str | None = None
    """An exercise whose restart file every point continues from (the spec's `restart_from`)."""
    notes: tuple[str, ...] = field(default_factory=tuple)


CELL_PARAMETERS = (8.0, 10.0, 12.0, 14.0, 16.0, 18.0)

SWEEPS: tuple[SweepExercise, ...] = (
    SweepExercise(
        id="water-cell-size",
        chapter="8.5",
        title="How far apart the periodic images of a molecule have to be",
        structure=fcc_water(12.0),
        spec=SweepSpec(
            name="Water cell size",
            backend_id="cppaw",
            label="Lattice parameter",
            unit="angstrom",
            base_values={
                **COURSE_WAVEFUNCTION,
                "task": "single_point",
                "start": "scratch",
                "nstep": 600,
                "empty_bands": 5,
                # The effect measured here is a few millihartree over the whole range, so each
                # run has to be converged well below that or the curve is the stopping rule's
                # noise rather than the physics. At the default ETOL the step from 10 to 12 A
                # came out six times smaller than the step from 12 to 14, which is not something
                # a monotone interaction does.
                "etol": 1e-9,
                "autoconv": 200,
            },
            points=[
                SweepPointSpec(x=a, structure=fcc_water(a)) for a in CELL_PARAMETERS
            ],
        ),
        shows="the total energy falling and then flattening off as the images stop interacting",
        notes=(
            (
                "The cell is what varies, not a parameter: a plane-wave code always computes a"
                " crystal, and the question is how large a cell has to be before the molecule in"
                " it stops feeling its own images. No schema value can express that, which is why"
                " a sweep point may carry a structure of its own."
            ),
            (
                "The course's rule of thumb is 6 A between any two atoms of neighbouring images,"
                " which for this fcc cell is a lattice parameter of about 12 A -- the value ch. 2"
                " uses. Its Fig. 8.5 shows the energy flat from roughly 12 A onwards."
            ),
            (
                "At the course's 30 Ry cutoff this sweep does not measure what it is meant to."
                " The energy falls in alternating steps of -2.9 and -0.5 mH instead of settling,"
                " and that is the basis set, not the images: it survives tightening ETOL by six"
                " orders of magnitude (bit-identical energies), it survives turning !ISOLATE off,"
                " the plane-wave count grows smoothly as a^3, and displacing the molecule by half"
                " a grid step moves the energy by only 0.033 mH, so it is not an egg-box effect"
                " either. Doubling the cutoff to 60 Ry collapses the steps to -0.32 and +0.08 mH"
                " and the curve is then flat from 12 A -- which is the answer the course gives."
                " Which G-shells fall inside a fixed cutoff sphere changes as the cell grows, and"
                " at 30 Ry that wobble is several times larger than the interaction being looked"
                " for. The exercise is kept at the course's own parameters; what the numbers mean"
                " is here."
            ),
        ),
    ),
)


def bcc_iron() -> Structure:
    """Chapter 8.2's reference: bcc iron, a=2.87 A, in its primitive (rhombohedral) cell.

    The course picks iron for the cutoff test because a late 3d transition metal is the worst
    case: hard to converge, and the 3d states are what make it hard.
    """
    a = 2.87
    return from_atoms(
        Atoms(
            "Fe",
            positions=[(0.0, 0.0, 0.0)],
            cell=[
                (-0.5 * a, 0.5 * a, 0.5 * a),
                (0.5 * a, -0.5 * a, 0.5 * a),
                (0.5 * a, 0.5 * a, -0.5 * a),
            ],
            pbc=True,
        ),
        name="bcc iron",
    )


#: Chapter 8.2's control settings: a metal, so Mermin occupations at T=0 and SAFEORTHO off, and
#: non-magnetic (NSPIN=1) even though iron is not -- the convergence of the cutoff is the subject,
#: and spin would only make each point slower.
IRON_REFERENCE = {
    "xc": 10,
    "epwpsi": 30.0,
    "cdual": 2.0,
    "task": "single_point",
    "start": "scratch",
    "nstep": 500,
    "empty_bands": 10,
    "occupations": "mermin",
    "electron_temperature": 0.0,
    "mermin_retard": 10.0,
    "safeortho": False,
    "psi_friction": 0.01,
    "psi_auto": True,
    "psi_auto_fric_minus": 0.3,
    "psi_auto_fact_minus": 0.97,
    "psi_auto_fric_plus": 0.3,
    "psi_auto_minfric": 0.02,
    "kpoint_mode": "density",
    "kpoint_r": 30.0,
    "npro_overrides": "Fe: 1 1 2",
    "lrhox": 4,
    "isolate": "never",
    "setup_type": ".75_6.0",
}

EXERCISES = (
    *EXERCISES,
    Exercise(
        id="iron-reference",
        chapter="8.2",
        title="A converged non-magnetic iron calculation to vary parameters from",
        structure=bcc_iron(),
        values=IRON_REFERENCE,
        shows="nothing on its own: it is the restart file chapter 8's sweeps continue from",
        notes=(
            (
                "The course's prose says to reduce the k-point density R to 20 while the deck it"
                " prints beside it says R=30. We follow the deck, which is the file that would"
                " actually have been run."
            ),
        ),
    ),
)


#: Chapter 4.4.2's starting geometry, built from the Lewis formula: the enol form of
#: malonaldehyde, with the hydrogen on one oxygen and an intramolecular hydrogen bond to the
#: other. Coordinates as the course prints them, in Angstrom.
MALONALDEHYDE = (
    ("C", (-1.22686, 0.20947, 0.20017)),
    ("C", (0.12930, 0.79738, 0.34620)),
    ("C", (1.30591, 0.21615, 0.02262)),
    ("H", (0.17192, 1.80149, 0.75751)),
    ("O", (-1.41386, -0.90880, -0.24663)),
    ("O", (1.43298, -1.02727, -0.49993)),
    ("H", (2.21462, 0.78505, 0.19292)),
    ("H", (0.70291, -1.62339, -0.69512)),
    ("H", (-2.08289, 0.80221, 0.50490)),
)


def malonaldehyde() -> Structure:
    """Chapter 4: malonaldehyde in a 14 A fcc cell.

    The course notes that regular fcc vectors need a lattice constant of at least 14 A for this
    molecule to clear its own images by 6 A -- a bigger molecule needs a bigger cell for the same
    isolation, which is the whole subject of ch. 8.5.
    """
    half = 7.0
    return from_atoms(
        Atoms(
            "".join(e for e, _ in MALONALDEHYDE),
            positions=[p for _, p in MALONALDEHYDE],
            cell=[(0.0, half, half), (half, 0.0, half), (half, half, 0.0)],
            pbc=True,
        ),
        name="malonaldehyde",
    )


#: Ch. 4 uses water's control file with one addition: fictitious masses. Carbon and oxygen at
#: 5 u and hydrogen at 2 u bring the vibrational timescales together so one time step suits all.
MALONALDEHYDE_MASSES = "C: 5; O: 5; H: 2"

EXERCISES = (
    *EXERCISES,
    Exercise(
        id="malonaldehyde-wavefunction",
        chapter="4.5",
        title="Optimize the electronic structure of malonaldehyde",
        structure=malonaldehyde(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "scratch",
            "nstep": 200,
            "empty_bands": 5,
            "npro_overrides": "H: 1 0 0; C: 2 2 1; O: 2 2 1",
            "atom_masses": MALONALDEHYDE_MASSES,
        },
        shows="the energy converging for a nine-atom molecule, and its HOMO-LUMO gap",
        notes=(
            (
                "The course gives C and O NPRO=2 2 1 and H NPRO=1 0 0, which is what our"
                " defaults would have chosen for C and O anyway; hydrogen is the one that"
                " differs."
            ),
        ),
    ),
    Exercise(
        id="malonaldehyde-relax",
        chapter="4.6",
        title="Relax malonaldehyde",
        structure=malonaldehyde(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "relax",
            "start": "restart",
            "nstep": 2000,
            "empty_bands": 5,
            "npro_overrides": "H: 1 0 0; C: 2 2 1; O: 2 2 1",
            "atom_masses": MALONALDEHYDE_MASSES,
            "psi_auto_fric_minus": 0.05,
            "psi_auto_fric_plus": 0.2,
            "atom_friction": 0.0,
            "atom_auto": True,
        },
        shows=(
            "the enol geometry: a short C-O and a long C=O, and the intramolecular hydrogen bond"
            " the H-bond layer should draw"
        ),
        continues="malonaldehyde-wavefunction",
    ),
    Exercise(
        id="malonaldehyde-orbitals",
        chapter="4.7",
        title="Malonaldehyde's orbitals, DOS and overlap populations",
        structure=malonaldehyde(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "restart",
            "nstep": 200,
            "empty_bands": 5,
            "npro_overrides": "H: 1 0 0; C: 2 2 1; O: 2 2 1",
            "atom_masses": MALONALDEHYDE_MASSES,
            "write_density": True,
            "grid_spacing": 0.3,
        },
        shows="the frontier orbitals, the DOS per element, and the C-O overlap populations",
        continues="malonaldehyde-relax",
        analysis=(
            (
                "orbitals",
                # the twelve occupied valence orbitals plus the first two empty ones
                {
                    "orbitals": [
                        {"band": b, "kpoint": 1, "spin": 1} for b in range(1, 15)
                    ]
                },
            ),
            (
                "dos",
                {
                    "broadening_ev": 0.172,
                    "de_ev": 0.01,
                    "projection": "element",
                    # ch. 4.7.5: the two C-O bonds, one of which is the enol C-O and the other
                    # the carbonyl C=O, so their overlap populations should not look alike
                    "coops": [
                        {
                            "id": "c1-o5",
                            "label": "C1 sp3 - O5 sp3",
                            "first": {"atom": 0, "type": "SP3", "toward": 4},
                            "second": {"atom": 4, "type": "SP3", "toward": 0},
                        },
                        {
                            "id": "c3-o6",
                            "label": "C3 sp3 - O6 sp3",
                            "first": {"atom": 2, "type": "SP3", "toward": 5},
                            "second": {"atom": 5, "type": "SP3", "toward": 2},
                        },
                    ],
                },
            ),
        ),
    ),
)


def silicon() -> Structure:
    """Chapter 6.3: silicon in the diamond structure at its experimental lattice constant.

    The course writes the two atoms at 0 and (1/4, 1/4, 1/4) *of the lattice constant*, which is
    Cartesian in units of LUNIT rather than fractional -- for fcc diamond that is a/4 along the
    body diagonal.
    """
    a = 5.431
    return from_atoms(
        Atoms(
            "Si2",
            positions=[(0.0, 0.0, 0.0), (0.25 * a, 0.25 * a, 0.25 * a)],
            cell=[
                (0.0, 0.5 * a, 0.5 * a),
                (0.5 * a, 0.0, 0.5 * a),
                (0.5 * a, 0.5 * a, 0.0),
            ],
            pbc=True,
        ),
        name="silicon",
    )


SILICON_REFERENCE = {
    "xc": 10,
    "epwpsi": 30.0,
    "cdual": 2.0,
    "task": "single_point",
    "start": "scratch",
    "nstep": 500,
    "empty_bands": 5,
    "psi_friction": 0.01,
    "psi_auto": True,
    "psi_auto_minfric": 0.02,
    "kpoint_mode": "density",
    "kpoint_r": 30.0,
    "npro_overrides": "Si: 2 2 1",
    "lrhox": 4,
    "isolate": "never",
    "setup_type": ".75_6.0",
}

SWEEPS = (
    *SWEEPS,
    SweepExercise(
        id="iron-cutoff",
        chapter="8.2",
        title="How large a plane-wave cutoff iron needs",
        structure=bcc_iron(),
        spec=SweepSpec(
            name="Iron cutoff",
            backend_id="cppaw",
            label="Plane-wave cutoff",
            unit="rydberg",
            key="epwpsi",
            base_values={**IRON_REFERENCE, "start": "restart"},
            points=[
                SweepPointSpec(x=cutoff, values={"epwpsi": cutoff})
                for cutoff in (20.0, 25.0, 30.0, 35.0, 40.0, 50.0, 60.0, 70.0)
            ],
        ),
        shows="the total energy against the cutoff, beside how fast the basis grows with it",
        continues="iron-reference",
        notes=(
            (
                "The course lists three ways to do this and picks the second: converge once from"
                " scratch, then run every cutoff from that restart file. That is what"
                " `restart_from` is, and it is not only faster -- every point starts from the"
                " same electronic state, so the curve shows the cutoff rather than eight"
                " independent convergences."
            ),
            (
                "Iron because a late 3d transition metal is the worst case. The course's own"
                ' command is `paw_scan -r "EPWPSI 20 25 30 35 40 50 60 70" -j 1 -w fast ./fe`;'
                " those are the eight points."
            ),
        ),
    ),
    SweepExercise(
        id="iron-dual-cutoff",
        chapter="8.3",
        title="How large a density cutoff iron needs",
        structure=bcc_iron(),
        spec=SweepSpec(
            name="Iron dual cutoff",
            backend_id="cppaw",
            label="Density cutoff factor",
            key="cdual",
            base_values=IRON_REFERENCE,
            points=[
                SweepPointSpec(x=dual, values={"cdual": dual})
                for dual in (2.0, 3.0, 4.0, 5.0, 6.0)
            ],
        ),
        shows="the energy flattening off past CDUAL=4, and the density basis growing with it",
        notes=(
            (
                "The course asks for independent calculations here rather than restarts, so this"
                " sweep has no `restart_from`: CDUAL changes the density representation, and"
                " restarting into a different one is not the same calculation."
            ),
            (
                "It also says what to expect: past CDUAL=4 only the exchange-correlation energy"
                " is still affected, because the Hartree and kinetic energies are exactly"
                " converged there."
            ),
        ),
    ),
    SweepExercise(
        id="silicon-kpoints",
        chapter="8.4, 6.3.6",
        title="How many k-points silicon needs",
        structure=silicon(),
        spec=SweepSpec(
            name="Silicon k-points",
            backend_id="cppaw",
            label="k-point density R",
            unit="bohr",
            key="kpoint_r",
            base_values=SILICON_REFERENCE,
            points=[
                SweepPointSpec(x=r, values={"kpoint_r": r})
                for r in (10.0, 20.0, 30.0, 40.0, 50.0)
            ],
        ),
        shows="the energy against the k-point density, and how many k-points each density means",
        notes=(
            (
                "R is a real-space length: the k-point grid is chosen so that the crystal"
                " repeated that far apart would be sampled. The course tries 20, 30 and 50 bohr"
                " and says 30-50 is the usual range; 10 is added at the bottom to show what too"
                " coarse looks like."
            ),
        ),
    ),
)


def aluminium() -> Structure:
    """Chapter 6.4: fcc aluminium at its experimental lattice constant, 4.05 A."""
    a = 4.05
    return from_atoms(
        Atoms(
            "Al",
            positions=[(0.0, 0.0, 0.0)],
            cell=[
                (0.0, 0.5 * a, 0.5 * a),
                (0.5 * a, 0.0, 0.5 * a),
                (0.5 * a, 0.5 * a, 0.0),
            ],
            pbc=True,
        ),
        name="aluminium",
    )


def nickel_oxide() -> Structure:
    """Chapter 7.3: NiO in the magnetic superstructure -- rock salt doubled along (111).

    The cell is what makes the antiferromagnet expressible at all: the two nickel atoms have to
    sit in *different* positions of the cell for their spins to differ.
    """
    a = 4.17
    return from_atoms(
        Atoms(
            "Ni2O2",
            positions=[
                (0.0, 0.0, 0.0),
                (a, a, a),
                (0.5 * a, 0.5 * a, 0.5 * a),
                (1.5 * a, 1.5 * a, 1.5 * a),
            ],
            cell=[(a, 0.5 * a, 0.5 * a), (0.5 * a, a, 0.5 * a), (0.5 * a, 0.5 * a, a)],
            pbc=True,
        ),
        name="nickel oxide",
    )


#: A metal: fractional occupations from a Mermin functional at T=0, and SAFEORTHO off.
METAL = {
    "occupations": "mermin",
    "electron_temperature": 0.0,
    "mermin_retard": 10.0,
    "safeortho": False,
}

EXERCISES = (
    *EXERCISES,
    Exercise(
        id="silicon-wavefunction",
        chapter="6.3.1",
        title="Silicon at its experimental lattice constant",
        structure=silicon(),
        values=SILICON_REFERENCE,
        shows="the total energy, the number of k-points, and the band gap of an insulator",
        analysis=(
            ("dos", {"broadening_ev": 0.2, "de_ev": 0.01, "projection": "atom"}),
        ),
        notes=(
            (
                "The course asks for the wave-function optimization only, not a relaxation:"
                " the point of this exercise is the experimental lattice constant, and finding"
                " the one DFT prefers comes later (ch. 6.3.5)."
            ),
        ),
    ),
    Exercise(
        id="aluminium",
        chapter="6.4.2",
        title="The electronic structure of a metal",
        structure=aluminium(),
        values={
            **SILICON_REFERENCE,
            **METAL,
            "empty_bands": 8,
            "npro_overrides": "Al: 1 1 1",
        },
        shows="partially filled bands, a Fermi level, and a DOS with no gap at it",
        analysis=(
            ("dos", {"broadening_ev": 0.2, "de_ev": 0.01, "projection": "atom"}),
        ),
        notes=(
            (
                "The course shifts the DOS energy axis to the Fermi level by hand (EZERO[EV])."
                " We do not need to: the Fermi level comes back with the spectrum and the plot"
                " marks it."
            ),
        ),
    ),
    Exercise(
        id="iron-ferromagnet",
        chapter="7.2.2",
        title="Is bcc iron magnetic?",
        structure=bcc_iron(),
        values={
            **IRON_REFERENCE,
            "spin_polarized": True,
            "total_spin": 2.0,
            "write_spin_density": True,
        },
        shows=(
            "a spin-resolved DOS and a moment to compare with the 2.22 Bohr magnetons measured,"
            " and an energy to compare with the non-magnetic iron-reference run"
        ),
        analysis=(
            ("dos", {"broadening_ev": 0.2, "de_ev": 0.01, "projection": "atom"}),
        ),
        notes=(
            (
                "The comparison is the exercise: this energy against `iron-reference`, which is"
                " the same calculation with NSPIN=1. If the magnetic one is lower, iron is"
                " magnetic at this lattice constant."
            ),
        ),
    ),
    Exercise(
        id="nio-symmetry-broken",
        chapter="7.3",
        title="Push NiO into an antiferromagnetic ordering",
        structure=nickel_oxide(),
        values={
            "xc": 10,
            "epwpsi": 30.0,
            "cdual": 2.0,
            "task": "single_point",
            "start": "scratch",
            "nstep": 500,
            "empty_bands": 4,
            "spin_polarized": True,
            "total_spin": 0.0,
            "kpoint_mode": "density",
            "kpoint_r": 20.0,
            "npro_overrides": "Ni: 2 1 2; O: 2 2 1",
            "lrhox": 4,
            "isolate": "never",
            "setup_type": ".75_6.0",
            "psi_friction": 0.01,
            "psi_auto": True,
            "psi_auto_minfric": 0.02,
            # the whole point: one nickel's d shell up, the other's down
            "orbital_potentials": "1 +0.1 D 1 2.0\n2 -0.1 D 1 2.0",
        },
        shows="nothing to be quoted: this is the nudge, and its result is not the answer",
        notes=(
            (
                "The two nickel atoms are equivalent, so nothing makes a spin-polarized run"
                " prefer the antiferromagnetic ordering that is its ground state. !ORBPOT breaks"
                " the symmetry. NiO is an insulator, so no Mermin functional and SAFEORTHO stays"
                " on -- unlike the metals in ch. 6.4 and 7.2."
            ),
        ),
    ),
    Exercise(
        id="nio-antiferromagnet",
        chapter="7.3",
        title="NiO's electronic structure, with the nudge removed",
        structure=nickel_oxide(),
        values={
            "xc": 10,
            "epwpsi": 30.0,
            "cdual": 2.0,
            "task": "single_point",
            "start": "restart",
            "nstep": 500,
            "empty_bands": 4,
            "spin_polarized": True,
            "total_spin": 0.0,
            "kpoint_mode": "density",
            "kpoint_r": 20.0,
            "npro_overrides": "Ni: 2 1 2; O: 2 2 1",
            "lrhox": 4,
            "isolate": "never",
            "setup_type": ".75_6.0",
            "psi_friction": 0.01,
            "psi_auto": True,
            "psi_auto_minfric": 0.02,
            "write_spin_density": True,
            # and here it is gone, which is the reason this is a second exercise
            "orbital_potentials": "",
        },
        shows="the total energy, HOMO, LUMO and gap of the antiferromagnet, and its spin density",
        continues="nio-symmetry-broken",
        analysis=(
            ("dos", {"broadening_ev": 0.2, "de_ev": 0.01, "projection": "atom"}),
        ),
        notes=(
            (
                "The course is explicit that the potential must be removed before any result is"
                " read, and that this second run continues from the first one's restart file."
                " A result that depended on the nudge would not be a result."
            ),
        ),
    ),
)


def sweep_by_id(exercise_id: str) -> SweepExercise:
    for e in SWEEPS:
        if e.id == exercise_id:
            return e
    known = ", ".join(e.id for e in SWEEPS)
    msg = f"no course sweep {exercise_id!r}; known: {known}"
    raise KeyError(msg)


def by_id(exercise_id: str) -> Exercise:
    for e in EXERCISES:
        if e.id == exercise_id:
            return e
    known = ", ".join(e.id for e in EXERCISES)
    msg = f"no course exercise {exercise_id!r}; known: {known}"
    raise KeyError(msg)
