"""The hands-on course as Atomscope inputs.

Each entry is one exercise from the CP-PAW hands-on course tutorial (Blöchl, Schade, ten Brink,
2019), given as the structure and the schema values that reproduce it. The course's own decks are
read as a specification: what is written here is parameters, and the deck is generated by our
CP-PAW plugin from them, so the example library exercises the same path a person using the
application does. `docs/course/inventory.md` says why the document itself is not in the repository.

Chapter numbers refer to that tutorial.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ase import Atoms
from atomscope.ase_bridge import from_atoms
from atomscope.model import Structure


@dataclass(frozen=True)
class Exercise:
    """One course exercise, ready to run."""

    id: str
    chapter: str
    title: str
    """What the exercise is for, in our words."""
    structure: Structure
    values: dict[str, Any]
    """Schema values that differ from the plugin's defaults, or that the course states outright."""
    shows: str
    """What the course asks you to look at, and therefore what the example has to visualize."""
    continues: str | None = None
    """An exercise whose restart file this one carries on from, as the course's chapters do."""
    notes: tuple[str, ...] = field(default_factory=tuple)
    """Where our deck departs from the course's, and why."""


def _water() -> Structure:
    """Chapter 2.5: one water molecule in a 12 Å fcc cell, the course's own coordinates.

    The cell is written as the three face-centred vectors of a cube of side 12 Å, which puts the
    nearest periodic image 7 Å away -- the course explains that the fcc cell is the best shape for
    an isolated molecule because it packs spheres most tightly for a given image separation.
    """
    return from_atoms(
        Atoms(
            "OH2",
            positions=[(0.0, 0.0, 0.0), (1.05, 0.0, 0.0), (0.0, 1.05, 0.0)],
            cell=[(0.0, 6.0, 6.0), (6.0, 0.0, 6.0), (6.0, 6.0, 0.0)],
            pbc=True,
        ),
        name="water",
    )


#: Values common to the course's early chapters: PBE, 30 Ry / dual 2, and the friction schedule
#: chapter 2.6 spells out. Our defaults already agree on the functional and the cutoffs.
COURSE_WAVEFUNCTION = {
    "xc": 10,
    "epwpsi": 30.0,
    "cdual": 2.0,
    "psi_friction": 0.01,
    "psi_auto": True,
    "psi_auto_fric_minus": 0.3,
    "psi_auto_fact_minus": 0.97,
    "psi_auto_fric_plus": 0.3,
    "psi_auto_minfric": 0.02,
    "lrhox": 4,
    "npro_overrides": "H: 1 0 0; O: 2 2 1",
    "setup_type": ".75_6.0",
    "isolate": "always",
    "kpoint_mode": "gamma",
}

EXERCISES: tuple[Exercise, ...] = (
    Exercise(
        id="water-wavefunction",
        chapter="2.7",
        title="Optimize the wave functions of a water molecule",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "scratch",
            "nstep": 200,
            "empty_bands": 5,
            "energy_trajectory": True,
        },
        shows="the total energy falling to a constant over the iterations, and the HOMO-LUMO gap",
        notes=(
            (
                "The course asks for at least one empty state so the gap can be read off, and"
                " notes that EMPTY=5 becomes six states because two real wave functions are"
                " packed into one complex one. We pass the 5 it asks for and let CP-PAW round,"
                " as it does for the course."
            ),
            (
                "The course quotes an absolute gap of 5.4665 eV. The binaries installed here give"
                " 5.3843 eV -- and so does the course's own deck, typed out and run directly, so"
                " the difference is the code or the setups this machine has, not our input."
            ),
        ),
    ),
)


def _water_relaxation() -> Exercise:
    """Chapter 2.8: relax the geometry once the wave functions are converged.

    The course continues from the restart file the previous run left, with lower wave-function
    friction and a friction on the atoms that decays while the energy keeps falling.
    """
    return Exercise(
        id="water-relax",
        chapter="2.8",
        title="Relax the atomic positions of water",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "relax",
            "start": "restart",
            "nstep": 2000,
            "empty_bands": 5,
            "psi_auto_fric_minus": 0.05,
            "psi_auto_fric_plus": 0.2,
            "atom_friction": 0.0,
            "atom_auto": True,
            "atom_auto_fric_minus": 0.0,
            "atom_auto_fact_minus": 0.9,
            "atom_auto_fric_plus": 0.01,
        },
        shows="the O-H bond length and the H-O-H angle the relaxation settles on",
        continues="water-wavefunction",
        notes=(
            (
                "The course starts this from the restart file the ch. 2.7 run left behind, so the"
                " example does too: it is the same working directory, with START=F."
            ),
            (
                "Result: 0.9815 A and 105.07 degrees, against the 0.981 A and 105.2 degrees the"
                " course reports for the same calculation. Experiment is 0.9572 A and 104.474."
            ),
        ),
    )


EXERCISES = (*EXERCISES, _water_relaxation())


def by_id(exercise_id: str) -> Exercise:
    for e in EXERCISES:
        if e.id == exercise_id:
            return e
    known = ", ".join(e.id for e in EXERCISES)
    msg = f"no course exercise {exercise_id!r}; known: {known}"
    raise KeyError(msg)
