"""The hands-on course as Atomscope inputs.

Each entry is one exercise from the CP-PAW hands-on course tutorial (Blöchl, Schade, ten Brink,
2019), given as the structure and the schema values that reproduce it. The course's own decks are
read as a specification: what is written here is parameters, and the deck is generated by our
CP-PAW plugin from them, so the example library exercises the same path a person using the
application does. `docs/course/inventory.md` says why the document itself is not in the repository.

Chapter numbers refer to that tutorial.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ase import Atoms
from atomscope.ase_bridge import from_atoms
from atomscope.calculations.sweeps import SweepPointSpec, SweepSpec
from atomscope.model import Structure


@dataclass(frozen=True)
class Exercise:
    """One course exercise, ready to run."""

    id: str
    chapter: str
    title: str
    """What the exercise is for, in our words."""
    structure: Structure
    values: dict[str, Any]
    """Schema values that differ from the plugin's defaults, or that the course states outright."""
    shows: str
    """What the course asks you to look at, and therefore what the example has to visualize."""
    analysis: tuple[tuple[str, dict[str, Any]], ...] = ()
    """Analysis tools to run once the calculation finishes: ("dos" | "bands" | "orbitals", opts)."""
    continues: str | None = None
    """An exercise whose restart file this one carries on from, as the course's chapters do."""
    notes: tuple[str, ...] = field(default_factory=tuple)
    """Where our deck departs from the course's, and why."""


def _water() -> Structure:
    """Chapter 2.5: one water molecule in a 12 Å fcc cell, the course's own coordinates.

    The cell is written as the three face-centred vectors of a cube of side 12 Å, which puts the
    nearest periodic image 7 Å away -- the course explains that the fcc cell is the best shape for
    an isolated molecule because it packs spheres most tightly for a given image separation.
    """
    return from_atoms(
        Atoms(
            "OH2",
            positions=[(0.0, 0.0, 0.0), (1.05, 0.0, 0.0), (0.0, 1.05, 0.0)],
            cell=[(0.0, 6.0, 6.0), (6.0, 0.0, 6.0), (6.0, 6.0, 0.0)],
            pbc=True,
        ),
        name="water",
    )


#: Values common to the course's early chapters: PBE, 30 Ry / dual 2, and the friction schedule
#: chapter 2.6 spells out. Our defaults already agree on the functional and the cutoffs.
COURSE_WAVEFUNCTION = {
    "xc": 10,
    "epwpsi": 30.0,
    "cdual": 2.0,
    "psi_friction": 0.01,
    "psi_auto": True,
    "psi_auto_fric_minus": 0.3,
    "psi_auto_fact_minus": 0.97,
    "psi_auto_fric_plus": 0.3,
    "psi_auto_minfric": 0.02,
    "lrhox": 4,
    "npro_overrides": "H: 1 0 0; O: 2 2 1",
    "setup_type": ".75_6.0",
    "isolate": "always",
    "kpoint_mode": "gamma",
}

EXERCISES: tuple[Exercise, ...] = (
    Exercise(
        id="water-wavefunction",
        chapter="2.7",
        title="Optimize the wave functions of a water molecule",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "scratch",
            "nstep": 200,
            "empty_bands": 5,
            "energy_trajectory": True,
        },
        shows="the total energy falling to a constant over the iterations, and the HOMO-LUMO gap",
        notes=(
            (
                "The course asks for at least one empty state so the gap can be read off, and"
                " notes that EMPTY=5 becomes six states because two real wave functions are"
                " packed into one complex one. We pass the 5 it asks for and let CP-PAW round,"
                " as it does for the course."
            ),
            (
                "The course quotes an absolute gap of 5.4665 eV. The binaries installed here give"
                " 5.3843 eV -- and so does the course's own deck, typed out and run directly, so"
                " the difference is the code or the setups this machine has, not our input."
            ),
        ),
    ),
)


def _water_relaxation() -> Exercise:
    """Chapter 2.8: relax the geometry once the wave functions are converged.

    The course continues from the restart file the previous run left, with lower wave-function
    friction and a friction on the atoms that decays while the energy keeps falling.
    """
    return Exercise(
        id="water-relax",
        chapter="2.8",
        title="Relax the atomic positions of water",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "relax",
            "start": "restart",
            "nstep": 2000,
            "empty_bands": 5,
            "psi_auto_fric_minus": 0.05,
            "psi_auto_fric_plus": 0.2,
            "atom_friction": 0.0,
            "atom_auto": True,
            "atom_auto_fric_minus": 0.0,
            "atom_auto_fact_minus": 0.9,
            "atom_auto_fric_plus": 0.01,
        },
        shows="the O-H bond length and the H-O-H angle the relaxation settles on",
        continues="water-wavefunction",
        notes=(
            (
                "The course starts this from the restart file the ch. 2.7 run left behind, so the"
                " example does too: it is the same working directory, with START=F."
            ),
            (
                "Result: 0.9815 A and 105.07 degrees, against the 0.981 A and 105.2 degrees the"
                " course reports for the same calculation. Experiment is 0.9572 A and 104.474."
            ),
        ),
    )


EXERCISES = (*EXERCISES, _water_relaxation())


def _water_orbitals() -> Exercise:
    """Chapter 3: the molecular orbitals, the electron density, and the density of states.

    The course exports the wave functions of a converged calculation as grids and looks at them
    as isosurfaces, then runs `paw_dos` over the same calculation for the total and projected
    density of states. Both come off the relaxed geometry of ch. 2.8.
    """
    return Exercise(
        id="water-orbitals",
        chapter="3.3, 3.5",
        title="Molecular orbitals, density and DOS of water",
        structure=_water(),
        values={
            **COURSE_WAVEFUNCTION,
            "task": "single_point",
            "start": "restart",
            "nstep": 200,
            "empty_bands": 5,
            "write_density": True,
            "grid_spacing": 0.25,
        },
        shows=(
            "isosurfaces of the four occupied orbitals and the first empty one, the electron"
            " density, and the total and projected density of states"
        ),
        continues="water-relax",
        analysis=(
            (
                "orbitals",
                {
                    "orbitals": [
                        {"band": b, "kpoint": 1, "spin": 1} for b in range(1, 7)
                    ]
                },
            ),
            # 2000 K in the course's !GRID BROADENING[K]; k_B T at 2000 K is 0.172 eV
            ("dos", {"broadening_ev": 0.172, "de_ev": 0.01, "projection": "atom"}),
        ),
        notes=(
            (
                "The course's .dcntl asks for the total DOS, oxygen s and p separately, and the"
                " two hydrogens together, then a COOP between the oxygen sp3 and the hydrogen s."
                " We write the total and a projection per atom and angular momentum, which covers"
                " the first four weights; the COOP is not something we can express yet."
            ),
        ),
    )


EXERCISES = (*EXERCISES, _water_orbitals())


#: The geometry our own ch. 2.8 run settled on: 0.9815 A, 105.07 degrees. The course's ch. 8.5
#: says to sweep the cell around "the relaxed structure from section 2.8", so this is it, written
#: down rather than read out of a run directory that may not exist.
RELAXED_WATER = (
    ("O", (0.0144, 0.0144, 0.0)),
    ("H", (0.9875, -0.1143, 0.0)),
    ("H", (-0.1143, 0.9875, 0.0)),
)


def fcc_water(lattice_parameter: float) -> Structure:
    """Relaxed water in a face-centred cell of cube edge ``lattice_parameter`` (A)."""
    half = lattice_parameter / 2.0
    return from_atoms(
        Atoms(
            "".join(e for e, _ in RELAXED_WATER),
            positions=[p for _, p in RELAXED_WATER],
            cell=[(0.0, half, half), (half, 0.0, half), (half, half, 0.0)],
            pbc=True,
        ),
        name=f"water in a {lattice_parameter:g} A fcc cell",
    )


@dataclass(frozen=True)
class SweepExercise:
    """A course exercise that is several runs and one curve."""

    id: str
    chapter: str
    title: str
    structure: Structure
    """The reference structure; points may bring their own."""
    spec: SweepSpec
    shows: str
    notes: tuple[str, ...] = field(default_factory=tuple)


CELL_PARAMETERS = (8.0, 10.0, 12.0, 14.0, 16.0, 18.0)

SWEEPS: tuple[SweepExercise, ...] = (
    SweepExercise(
        id="water-cell-size",
        chapter="8.5",
        title="How far apart the periodic images of a molecule have to be",
        structure=fcc_water(12.0),
        spec=SweepSpec(
            name="Water cell size",
            backend_id="cppaw",
            label="Lattice parameter",
            unit="angstrom",
            base_values={
                **COURSE_WAVEFUNCTION,
                "task": "single_point",
                "start": "scratch",
                "nstep": 600,
                "empty_bands": 5,
                # The effect measured here is a few millihartree over the whole range, so each
                # run has to be converged well below that or the curve is the stopping rule's
                # noise rather than the physics. At the default ETOL the step from 10 to 12 A
                # came out six times smaller than the step from 12 to 14, which is not something
                # a monotone interaction does.
                "etol": 1e-9,
                "autoconv": 200,
            },
            points=[
                SweepPointSpec(x=a, structure=fcc_water(a)) for a in CELL_PARAMETERS
            ],
        ),
        shows="the total energy falling and then flattening off as the images stop interacting",
        notes=(
            (
                "The cell is what varies, not a parameter: a plane-wave code always computes a"
                " crystal, and the question is how large a cell has to be before the molecule in"
                " it stops feeling its own images. No schema value can express that, which is why"
                " a sweep point may carry a structure of its own."
            ),
            (
                "The course's rule of thumb is 6 A between any two atoms of neighbouring images,"
                " which for this fcc cell is a lattice parameter of about 12 A -- the value ch. 2"
                " uses. Its Fig. 8.5 shows the energy flat from roughly 12 A onwards."
            ),
            (
                "At the course's 30 Ry cutoff this sweep does not measure what it is meant to."
                " The energy falls in alternating steps of -2.9 and -0.5 mH instead of settling,"
                " and that is the basis set, not the images: it survives tightening ETOL by six"
                " orders of magnitude (bit-identical energies), it survives turning !ISOLATE off,"
                " the plane-wave count grows smoothly as a^3, and displacing the molecule by half"
                " a grid step moves the energy by only 0.033 mH, so it is not an egg-box effect"
                " either. Doubling the cutoff to 60 Ry collapses the steps to -0.32 and +0.08 mH"
                " and the curve is then flat from 12 A -- which is the answer the course gives."
                " Which G-shells fall inside a fixed cutoff sphere changes as the cell grows, and"
                " at 30 Ry that wobble is several times larger than the interaction being looked"
                " for. The exercise is kept at the course's own parameters; what the numbers mean"
                " is here."
            ),
        ),
    ),
)


def sweep_by_id(exercise_id: str) -> SweepExercise:
    for e in SWEEPS:
        if e.id == exercise_id:
            return e
    known = ", ".join(e.id for e in SWEEPS)
    msg = f"no course sweep {exercise_id!r}; known: {known}"
    raise KeyError(msg)


def by_id(exercise_id: str) -> Exercise:
    for e in EXERCISES:
        if e.id == exercise_id:
            return e
    known = ", ".join(e.id for e in EXERCISES)
    msg = f"no course exercise {exercise_id!r}; known: {known}"
    raise KeyError(msg)
